### ISSUE TITLE
trigger_and_get_schedule() should accept flex_model and flex_context dicts

### ISSUE THREAD

**Issue by nhoening** [FlexMeasures/flexmeasures-client#54]
I would like to use these dicts in the client, as well, rather than require a long list of parameters. See https://flexmeasures.readthedocs.io/en/latest/api/notation.html#flex-context

Next to consistency, it would then also be easier for `trigger_and_get_schedule` to support other types of schedulers, rather than only `trigger_storage_schedule()`. That's also the major reason why we implemented those (when considering the FM API - similar thoughts work for the client).

Do we already need to support backwards-compatibility? Maybe not in such early times. We could support the old signature for one release by failing with a notice how to use it from now on.

**Comment by nhoening** [comment]
We can also follow the way of the CLI, and have one dedicated function per supported scheduler.

**Comment by nhoening** [comment]
@GustaafL Hasn't this been solved by #65

**Comment by GustaafL** [comment]
Correct, closed by #65 . Thanks!
