### ISSUE TITLE
Cannot import FlexMeasuresClient 

### ISSUE THREAD

**Issue by rhpijnacker** [FlexMeasures/flexmeasures-client#85]
I tried importing FlexMeasuresClient like I would any python module:

```
from flexmeasures_client import FlexMeasuresClient
```

However, this does not appear to work. I get this error:

```
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    from flexmeasures_client import FlexMeasuresClient
  File "/.../lib/python3.9/site-packages/flexmeasures_client/__init__.py", line 3, in <module>
    from flexmeasures_client.client import FlexMeasuresClient  # noqa F401
  File "/.../lib/python3.9/site-packages/flexmeasures_client/client.py", line 43, in <module>
    class FlexMeasuresClient:
  File "/.../lib/python3.9/site-packages/flexmeasures_client/client.py", line 58, in FlexMeasuresClient
    session: ClientSession = ClientSession()
  File "/.../lib/python3.9/site-packages/aiohttp/client.py", line 296, in __init__
    loop = loop or asyncio.get_running_loop()
RuntimeError: no running event loop
```

It look like importing only works inside an event loop, which is very unusual.

**Comment by nhoening** [comment]
Thanks for reporting.

`session: ClientSession = ClientSession()`

should not be in that place. I will provide a fix.

**Comment by rhpijnacker** [comment]
> @rhpijnacker can you let me know if #87 fixes the issue?

Yes, I can load the module outside the event loop now. Thanks for the update.

**Comment by nhoening** [comment]
@rhpijnacker Do you agree with the choice in this PR that the session is already established when the Client is made? (I took that choice over from another open PR by Victor).

Maybe it adds problems for the developer, and it suffices that all functionality which runs requests makes sure we have a session? (see line 132).

Truth be told, I do not have much experience in async programming, and this issue came up for me. I might not see the whole picture ...

**Comment by rhpijnacker** [comment]
I cannot really judge whether that makes sense. If it does not hurt to create the session immediately, then I guess that's ok.

**Comment by nhoening** [comment]
It doesn't clash with what you are doing right now, so I guess that is a good validation.

**Comment by nhoening** [comment]
@rhpijnacker This issue (and the other one you raised) is now part of the latest flexmeasures-client release, available on pypi

**Comment by rhpijnacker** [comment]
Thanks!
