### ISSUE TITLE
FlexMeasures API version deprecation and support in the FlexMeasures Client

### ISSUE THREAD

**Issue by GustaafL** [FlexMeasures/flexmeasures-client#9]
- How should we handle API deprecation?
- Should the client class itself have a version matching the API version? I think it should be the case because we are relying on some API version to develop the methods.

**Comment by Flix6x** [comment]
Supported API versions for a given FlexMeasures server can be gotten from calling the server's `/api` endpoint, see https://flexmeasures.readthedocs.io/en/latest/api/introduction.html#main-endpoint-and-api-versions
```
import requests
res = requests.get("https://company.flexmeasures.io/api")
res.json()
{'flexmeasures_version': '0.9.0',
 'message': 'For these API versions endpoints are available. An authentication token can be requested at: /api/requestAuthToken. For a list of services, see https://flexmeasures.readthedocs.io',
 'status': 200,
 'versions': ['v1', 'v1_1', 'v1_2', 'v1_3', 'v2_0', 'v3_0']
}
```

And we might then want the client to keep track of which FlexMeasures versions it supports.

**Comment by nhoening** [comment]
Let's update (or remove) this issue, as FM has deprecated all but v3 for now. 

We can fix to v3 for a while.
